#ifndef PLJIT_DEADCODEELIMINATIONOPTIMIZATIONPASS_HPP
#define PLJIT_DEADCODEELIMINATIONOPTIMIZATIONPASS_HPP

namespace ast {

class DeadCodeEliminationOptimizationPass {
};

} // namespace ast

#endif //PLJIT_DEADCODEELIMINATIONOPTIMIZATIONPASS_HPP
